use_frameworks!

platform :ios, '10.0'

target 'YPUIKit-ObjC_Example' do
  
  pod 'YPUIKit-ObjC', :path => '../'
  
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= []
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'YP_USE_CAMERA=1'
    end
  end
end
